function changeToAr() {

    document.getElementById("heroText1").innerHTML = "أول إمبراطورية شوهدت في فضاء Blockchain و DeFi! هذا الآلية عالية الكفاءة لوضع الكل في واحد في رمز مميز يُدعى رمز الإمبراطورية ، رؤية جديدة ، مهمة جديدة ، حياة جديدة."
    document.getElementById("heroText2").innerHTML = "معًا ، يمكننا الاستمرار في التسلق للوصول إلى أعلى مستوى في الإمبراطورية";
    document.getElementById("heroLink1").innerHTML = "فحص BSC"
    document.getElementById("heroLink2").innerHTML = "ورق ابيض"
    document.getElementById("nameId").innerHTML = "الاسم: EMPIRE TOKEN"
    document.getElementById("typeId").innerHTML = "النوع: ERC20"
    document.getElementById("symbolId").innerHTML = "الرمز: إمباير"
    document.getElementById("supplyId").innerHTML = "العرض: 1،000،000،000"
    document.getElementById("decimalId").innerHTML = "عشري: 9"
    document.getElementById("explore").innerHTML = "يكتشف"


}
function changeToEn() {
    document.getElementById("home").innerHTML = "Home"
    document.getElementById("Tokenomics").innerHTML = "Tokenomics"
    document.getElementById("Audit").innerHTML = "Audit"
    document.getElementById("dex").innerHTML = "DEX"
    document.getElementById("nft").innerHTML = "NFT Marketplace"
    document.getElementById("price").innerHTML = "Price Chart"
    document.getElementById('blog').innerHTML = "Blogs & News"
    document.getElementById('buy').innerHTML = "Buy on PancakeSwap"
    document.getElementById('curLang').innerHTML = "ENG"
    document.getElementById("heroText1").innerHTML = " We are creating a digital world like no other. Developing dApps and creating solutions is our way to expand the Empire and climb to the top"
    document.getElementById("heroText2").innerHTML = "Hold the ambitious and transparent Empire Token";
    document.getElementById("heroLink1").innerHTML = "BSC Scan"
    document.getElementById("heroLink2").innerHTML = "WHITE PAPER"
    document.getElementById("nameId").innerHTML = "Name: EMPIRE TOKEN"
    document.getElementById("typeId").innerHTML = "Type : BEP-20"
    document.getElementById("symbolId").innerHTML = "Symbol : EMPIRE"
    document.getElementById("supplyId").innerHTML = "Supply : 1,000,000,000 "
    document.getElementById("decimalId").innerHTML = "Decimal: 9"
    document.getElementById("explore").innerHTML = "EXPLORE"
    document.getElementById("useCaseText").innerHTML = "How Empire"
    document.getElementById("useCaseTextBlue").textContent = "Can be Used"
    document.getElementById("caseTitle1").innerHTML = "EMPIRE NFT MARKETPLACE"
    document.getElementById("caseText1").innerHTML = "Marketplace . Auction, licencing and many more Empire brings the world of non-fungible token (NFTs) to diffrent level , with new vision into this place"
    document.getElementById("caseTitle2").innerHTML = "EMPIRE DEX"
    document.getElementById("caseText2").innerHTML = "Marketplace . Auction, licencing and many more Empire brings the world of non-fungible token (NFTs) to diffrent level , with new vision into this place"
    document.getElementById("promiseText").innerHTML = "Only the"
    document.getElementById("promiseTextBlue").innerHTML = "Highest Standards"
    document.getElementById("transparency").innerHTML = "Full Transparency"
    document.getElementById("marketing").innerHTML = "Marketing & More Marketing"
    document.getElementById("innovate").innerHTML = "Innovative Thinking"
    document.getElementById("real").innerHTML = "Real Life Application"
    document.getElementById('xp').innerHTML = "Experienced Team"
    document.getElementById("con").innerHTML = "Contract Audit"
    document.getElementById('roadmapHead').innerHTML = "Roadmap"
    document.getElementById('roadmapText').innerHTML = "Where we"
    document.getElementById('roadmapTextBlue').innerHTML = "Are Going"
    document.getElementById("youAre").innerHTML = "You Are Here"
    document.getElementById("thinkText").innerHTML = "What"
    document.getElementById("thinkTextBlue").innerHTML = "We Think"
    document.getElementById('vision').innerHTML = "Our Vision"
    document.getElementById('visionText').innerHTML = ""
    document.getElementById('mission').innerHTML = "Our mission"
    document.getElementById('missionText').innerHTML = ""
    document.getElementById('value').innerHTML = "Our Value"
    document.getElementById('valueText').innerHTML = ""
    document.getElementById("why").innerHTML = "Why"
    document.getElementById("whyBlue").innerHTML = "Empire Token"
    document.getElementById("strUseCases").innerHTML = "Strong Use Cases"
    document.getElementById("strMkt").innerHTML = "Strong Market"
    document.getElementById("atLp").innerHTML = "Automatic LP"
    document.getElementById("rfi").innerHTML = "RFI Static Rewards"
    document.getElementById("fv").innerHTML = " Futuristic Vision"
    document.getElementById("founder").innerHTML = "About"
    document.getElementById("founderBlue").innerHTML = "The Founder"
    document.getElementById("name").innerHTML = "Dulla"
    document.getElementById("des").innerHTML = "Founder & CEO"
    document.getElementById("nameText").innerHTML = ""
    document.getElementById("blogHead").innerHTML = "Blogs"
}